# Generated by Django 4.0.4 on 2022-06-12 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(help_text='URL для поиска причина жалобы по её наименованию', max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Причина жалобы',
                'verbose_name_plural': 'Причины жалоб',
                'ordering': ('-datetime_updated',),
            },
        ),
        migrations.CreateModel(
            name='ComplainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('content', models.TextField(verbose_name='Текст')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='n_complains', to='news.news', verbose_name='Новость')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='complains', to=settings.AUTH_USER_MODEL, verbose_name='Владелец жалобы')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='complains', to='complains.complainreason', verbose_name='Причина жалобы')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ('-datetime_updated',),
            },
        ),
    ]
