# Generated by Django 4.0.4 on 2022-06-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complainnews',
            options={'ordering': ('-datetime_updated',), 'verbose_name': 'Жалоба новости', 'verbose_name_plural': 'Жалобы новостей'},
        ),
    ]
