# Generated by Django 4.0.4 on 2022-06-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='slug',
            field=models.SlugField(help_text='URL для поиска на основе никнейма исполнителя', max_length=100, unique=True, verbose_name='Url'),
        ),
    ]
