# Generated by Django 4.0.4 on 2022-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privilege',
            options={'ordering': ('-datetime_updated',), 'verbose_name': 'Привилегия (В группе)', 'verbose_name_plural': 'Привилегии (В группах)'},
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='URL для поиска группы (будет в нижнем регистре)', max_length=100, unique=True, verbose_name='URL (на группу)'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='URL для поиска привилегий по названию', unique=True, verbose_name='URL (shared link)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Наименование'),
        ),
    ]
