# Generated by Django 4.0.4 on 2022-06-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('name', models.CharField(max_length=250, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='documents/videos/%Y/%m/%d', verbose_name='Видео файл')),
                ('keepers', models.ManyToManyField(blank=True, related_name='added_videos', to=settings.AUTH_USER_MODEL, verbose_name='Имеется пользователями')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_videos', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видосики',
                'ordering': ('-datetime_updated',),
            },
        ),
    ]
