# Generated by Django 4.0.4 on 2022-07-11 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import videos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('name', models.CharField(max_length=250, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='documents/videos/%Y/%m/%d', validators=[videos.validators.video_format_validator], verbose_name='Видео файл')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видосики',
                'ordering': ('-datetime_updated',),
            },
        ),
        migrations.CreateModel(
            name='VideoKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Добавленное видео',
                'verbose_name_plural': 'Добавленные видео',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='video',
            name='keepers',
            field=models.ManyToManyField(blank=True, related_name='added_videos', through='videos.VideoKeeper', to=settings.AUTH_USER_MODEL, verbose_name='Имеется пользователями'),
        ),
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_videos', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddConstraint(
            model_name='videokeeper',
            constraint=models.UniqueConstraint(fields=('video', 'user'), name='unique_video_user'),
        ),
        migrations.AlterIndexTogether(
            name='videokeeper',
            index_together={('video', 'user')},
        ),
    ]
