# Generated by Django 4.0.4 on 2022-06-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-datetime_updated',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
