# Generated by Django 4.0.4 on 2022-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='locations_city_unique_relationships'),
        ),
    ]
