# Generated by Django 4.0.4 on 2022-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание фото'),
        ),
    ]
