# Generated by Django 4.0.4 on 2022-06-03 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name': 'Друг', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(help_text='URL по юзернейму которого происходит поиск', max_length=150, unique=True, verbose_name='Url (by username)'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кого добавляет'),
        ),
    ]
