# Generated by Django 4.0.4 on 2022-06-04 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_friends_options_alter_customuser_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='phone_format', message='Формат вашего телефона не совпадает', regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7}$')], verbose_name='Номер телефона'),
        ),
    ]
